# Generated by Django 4.0.2 on 2022-02-26 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree',
        ),
        migrations.AddField(
            model_name='teacher',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 26, 10, 46, 18, 524897, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(default=datetime.datetime(2022, 2, 26, 10, 49, 27, 260253, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
