# Generated by Django 4.0.2 on 2022-02-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_teacher_options_remove_teacher_degree_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['surname']},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='created',
        ),
    ]
